### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by rtorr** [skipperjs/skipper-postgresql#2]
Brand new database
postgres version: psql (PostgreSQL) 9.5.1
node version: v5.6.0
npm version: 3.6.0
sails version: ~0.12.2
sails-postgresql: ^0.12.1
skipper-postgresql: ^0.13.2

`api/controllers/FileController.js`

```
/**
 * FileController
 *
 * @description :: Server-side logic for managing files
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */

module.exports = {
  upload: function  (req, res) {
    req.file('file').upload(sails.config.skipper, function (err, files) {
      if (err) return res.negotiate(err);
    })
  }
};
```

`config/skipper.js`

```
module.exports.skipper = {
 adapter: require('skipper-postgresql'),
 connection: {
    host: 'localhost',
    user: 'XXXX',
    password: 'XXXX',
    database: 'XXXX'
 },
 fileTable: 'file'
};
```

with `api/models/File.js looking like

```
module.exports = {

};
```

```
error: Sending 500 ("Server Error") response: 
 error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - column "data" of relation "file" does not exist
    at Connection.parseE (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20) { [error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - column "data" of relation "file" does not exist]
  name: 'error',
  length: 113,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '21',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '943',
  routine: 'checkInsertTargets' }
Unhandled rejection error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - column "data" of relation "file" does not exist
    at Connection.parseE (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20)
```

with `api/models/File.js` looking like

```
var uuid = require('node-uuid');

module.exports = {

  attributes: {
    id: {
      type: 'text',
      primaryKey: true,
      unique: true,
      defaultsTo: function () {
        return uuid.v4();
      }
    },
    author: {
      model: 'user'
    },
    fd: 'string',
    size: 'integer',
    filename: 'string',
    type: 'string',
    data: 'text',
    dirname: 'binary'
  },
  newFile: function (inputs, cb) {
    inputs.files.map(function (file) {
      file.author = inputs.author;
      return file;
    });
    console.log(inputs.files)
    File.create(inputs.files).exec(function (err, new_files) {
      User.find(inputs.author)
        .populate('files')
        .populate('auth')
        .exec(function (e, r) {
          new_files.map(function (f) {
            r[0].files.add(f.id);
          });
          r[0].save(function (err, res) {
            return cb(err, new_files);
          });
        });
    });
  }
};

```

``````
error: Sending 500 ("Server Error") response: 
 error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - invalid byte sequence for encoding "UTF8": 0x00
    at Connection.parseE (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20) { [error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - invalid byte sequence for encoding "UTF8": 0x00]
  name: 'error',
  length: 108,
  severity: 'ERROR',
  code: '22021',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'wchar.c',
  line: '2017',
  routine: 'report_invalid_encoding' }
Unhandled rejection error: insert into "file" ("data", "dirname", "fd") values ($1, $2, $3) returning "fd", "dirname" - invalid byte sequence for encoding "UTF8": 0x00
    at Connection.parseE (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/rtorr/personal/catchall/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20)```
``````

**Comment by tjwebb** [comment]
Seems fairly straightforward to me: 

```
column "data" of relation "file" does not exist
```

Does your file table not have a `data` column?

**Comment by rtorr** [comment]
Nope

**Comment by rtorr** [comment]
Do I been to manually add one? If so, what type?
